## Wayfair ecommerce data analysis

In [25]:
# import packages
import pandas as pd
from data_profiling import ProfileReport

In [26]:
# import data
customers = pd.read_csv(r"C:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\data\customers.csv", parse_dates=['signup_date'])

In [27]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   datetime64[ns]
 2   state                3600 non-null   object
 3   acquisition_channel  3600 non-null   object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 112.6+ KB

In [28]:
customers

      customer_id signup_date state acquisition_channel
0               1  2024-09-13    CO      organic_search
1               2  2025-10-21    IL         paid_search
2               3  2025-01-17    AZ            referral
3               4  2024-06-23    FL         paid_social
4               5  2025-04-08    IL         paid_social
...           ...         ...   ...                 ...
3595         3596  2025-11-14    LA            referral
3596         3597  2025-05-27    WA         paid_search
3597         3598  2024-06-03    CA         paid_search
3598         3599  2025-08-23    LA      organic_search
3599         3600  2024-10-19    NY      organic_search

[3600 rows x 4 columns]

In [29]:
c_dupes = customers.duplicated()
print(c_dupes.sum())

0

In [30]:
products = pd.read_csv(r"C:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\data\products.csv")

In [31]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     int64
 1   product_name  90 non-null     object
 2   category      90 non-null     object
 3   list_price    90 non-null     float64
 4   unit_cost     90 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 3.6+ KB

In [32]:
p_dupes = products.duplicated()
print(p_dupes.sum())

0

In [33]:
orders = pd.read_csv(r"C:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\data\orders.csv", parse_dates=['order_date'])

In [34]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   datetime64[ns]
 3   status          9245 non-null   object
 4   payment_method  9245 non-null   object
 5   discount_code   1411 non-null   object
 6   shipping_fee    9245 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 505.7+ KB

In [35]:
orders.isna().sum()

order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7834
shipping_fee         0
dtype: int64

In [36]:
o_dupes = orders.duplicated()
print(o_dupes.sum())

38

In [37]:
orders

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
2,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00
3,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00
4,100005,3452,2024-01-01 17:44:03,completed,gift_card,NaN,0.00
...,...,...,...,...,...,...,...
9240,109203,3499,2025-12-31 16:50:18,completed,credit_card,HOLIDAY20,6.95
9241,109204,3410,2025-12-31 17:40:58,completed,credit_card,HOLIDAY20,0.00
9242,109205,2911,2025-12-31 18:21:51,completed,credit_card,NaN,0.00
9243,109206,1157,2025-12-31 21:38:59,completed,credit_card,NaN,6.95
9244,109207,2208,2025-12-31 23:23:29,completed,paypal,HOLIDAY20,0.00

In [38]:
# view duplicates
orders[orders.duplicated(keep=False)]

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
47,100048,3320,2024-01-06 16:37:36,completed,credit_card,NaN,6.95
130,107012,870,2025-08-12 10:39:49,completed,apple_pay,NaN,0.00
303,100303,853,2024-02-03 08:33:22,completed,apple_pay,NaN,0.00
310,106199,3072,2025-06-09 23:50:03,completed,credit_card,NaN,6.95
479,104695,443,2025-02-14 11:56:23,completed,credit_card,NaN,0.00
...,...,...,...,...,...,...,...
8737,107493,1664,2025-09-21 23:42:50,completed,apple_pay,NaN,6.95
9032,102517,1254,2024-08-28 20:08:41,completed,paypal,NaN,0.00
9104,109068,1981,2025-12-20 13:27:25,completed,credit_card,HOLIDAY20,6.95
9122,108138,1241,2025-11-07 12:15:41,returned,gift_card,NaN,0.00
9124,109087,3358,2025-12-22 08:35:44,completed,credit_card,HOLIDAY20,0.00

In [39]:
# drop duplicates
orders = orders.drop_duplicates()

In [40]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9207 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9207 non-null   int64
 1   customer_id     9207 non-null   int64
 2   order_date      9207 non-null   datetime64[ns]
 3   status          9207 non-null   object
 4   payment_method  9207 non-null   object
 5   discount_code   1405 non-null   object
 6   shipping_fee    9207 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 575.4+ KB

In [41]:
order_items = pd.read_csv(r"C:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\data\order_items.csv")

In [42]:
order_items

       order_id  product_id  quantity  unit_price  discount_amount
0        100001        1031         1       38.99             0.00
1        100002        1087         1       45.99             0.00
2        100002        1072         1      141.99             0.00
3        100003        1048         1      139.99             0.00
4        100004        1083         1       19.99             2.00
...         ...         ...       ...         ...              ...
15603    109204        1070         1      129.14            25.83
15604    109205        1072         2      149.09             0.00
15605    109206        1071         1       10.49             0.00
15606    109207        1023         2      142.79            57.12
15607    109207        1043         1      134.39            26.88

[15608 rows x 5 columns]

In [43]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15608 entries, 0 to 15607
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         15608 non-null  int64
 1   product_id       15608 non-null  int64
 2   quantity         15608 non-null  int64
 3   unit_price       15409 non-null  float64
 4   discount_amount  15608 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 609.8 KB

In [44]:
oi_dupes = order_items.duplicated()
print(oi_dupes.sum())

0

## Calculation of revenue

Only completed orders (from status column in orders table will count as revenue).  Order figures are in order_items table.  Hence we need to left join order_items to orders.  

total price = (quantity * unit price) - discount

The calculation of revenue for each order will be as follows;

revenue = total price - shipping fee

In [45]:
full_orders = pd.merge(order_items, orders, left_on='order_id', right_on='order_id', how='left')

In [46]:
full_orders

,order_id,product_id,quantity,unit_price,discount_amount,customer_id,order_date,status,payment_method,discount_code,shipping_fee
0,100001,1031,1,38.99,0.00,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95
1,100002,1087,1,45.99,0.00,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
2,100002,1072,1,141.99,0.00,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
3,100003,1048,1,139.99,0.00,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00
4,100004,1083,1,19.99,2.00,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00
...,...,...,...,...,...,...,...,...,...,...,...
15603,109204,1070,1,129.14,25.83,3410,2025-12-31 17:40:58,completed,credit_card,HOLIDAY20,0.00
15604,109205,1072,2,149.09,0.00,2911,2025-12-31 18:21:51,completed,credit_card,NaN,0.00
15605,109206,1071,1,10.49,0.00,1157,2025-12-31 21:38:59,completed,credit_card,NaN,6.95
15606,109207,1023,2,142.79,57.12,2208,2025-12-31 23:23:29,completed,paypal,HOLIDAY20,0.00
15607,109207,1043,1,134.39,26.88,2208,2025-12-31 23:23:29,completed,paypal,HOLIDAY20,0.00

In [47]:
full_orders['total_price'] = (full_orders['quantity'] * full_orders['unit_price']) - full_orders['discount_amount']

In [48]:
full_orders

,order_id,product_id,quantity,unit_price,discount_amount,customer_id,order_date,status,payment_method,discount_code,shipping_fee,total_price
0,100001,1031,1,38.99,0.00,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95,38.99
1,100002,1087,1,45.99,0.00,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00,45.99
2,100002,1072,1,141.99,0.00,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00,141.99
3,100003,1048,1,139.99,0.00,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00,139.99
4,100004,1083,1,19.99,2.00,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00,17.99
...,...,...,...,...,...,...,...,...,...,...,...,...
15603,109204,1070,1,129.14,25.83,3410,2025-12-31 17:40:58,completed,credit_card,HOLIDAY20,0.00,103.31
15604,109205,1072,2,149.09,0.00,2911,2025-12-31 18:21:51,completed,credit_card,NaN,0.00,298.18
15605,109206,1071,1,10.49,0.00,1157,2025-12-31 21:38:59,completed,credit_card,NaN,6.95,10.49
15606,109207,1023,2,142.79,57.12,2208,2025-12-31 23:23:29,completed,paypal,HOLIDAY20,0.00,228.46
15607,109207,1043,1,134.39,26.88,2208,2025-12-31 23:23:29,completed,paypal,HOLIDAY20,0.00,107.51